/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.gavin.ui;

import cn.gavin.ReadUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 *
 * @author luoyuan
 */
public class OptionView extends JPanel {

private final ReadUtils readUtils;

/**
     * Creates new form OptionView
     */
    public OptionView(ReadUtils readUtils) {
        this.readUtils = readUtils;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        userName = new JTextField();
        jLabel3 = new JLabel();
        sourcePath = new JTextField();
        selectPath = new JButton();
        password = new JPasswordField();
        conform = new JButton();
        cancle = new JButton();

        jLabel1.setText("数据库文件");

        jLabel2.setText("用户名");

        userName.setText(readUtils.read("user"));

        jLabel3.setText("密码");

        sourcePath.setText(readUtils.read("file"));

        selectPath.setFont(new Font("宋体", 0, 10)); // NOI18N
        selectPath.setText("浏览");

        password.setText(readUtils.read("password"));

        conform.setText("确认");
        conform.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                conformActionPerformed(e);
            }
        });
        cancle.setText("取消");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(
                                                        GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                        GroupLayout.Alignment.LEADING)
                                                        .addComponent(password, GroupLayout.PREFERRED_SIZE,
                                                                78, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(userName, GroupLayout.PREFERRED_SIZE,
                                                                78, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(cancle)
                                                                        .addComponent(sourcePath,
                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                182,
                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(selectPath))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(conform)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(selectPath, GroupLayout.DEFAULT_SIZE, 22,
                                                        Short.MAX_VALUE)
                                                .addGap(1, 1, 1))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(sourcePath, GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(userName, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(password, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(conform)
                                        .addComponent(cancle))
                                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void conformActionPerformed(ActionEvent e) {
    readUtils.write("user", userName.getText());
    readUtils.write("password", new String(password.getPassword()));
    readUtils.write("file", sourcePath.getText());
    try {
        readUtils.save();
        readUtils.reOpen();
    } catch (IOException e1) {
        e1.printStackTrace();
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancle;
    private JButton conform;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPasswordField password;
    private JButton selectPath;
    private JTextField sourcePath;
    private JTextField userName;
    // End of variables declaration//GEN-END:variables
}
