/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.gavin.ui;

import cn.gavin.ReadUtils;
import cn.gavin.action.TransferToSqlite;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;

/**
 * @author luoyuan
 */
public class Register extends JFrame {

/**
 * Creates new form Register
 */
public Register() {
	initComponents();
	setLocationRelativeTo(null);

}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

	jLabel3 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        registButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userAlise = new javax.swing.JTextField();
        loadKeyButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optionButton = new javax.swing.JMenuItem();
        quitButton = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("注册用户");

        key.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        key.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        key.setText("123dff-1dddd23-1ddd23-12ddd3-123");

        registButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        registButton.setText("注册");
        registButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("点击注册后将会根据用户的标识码");
        jLabel2.setEnabled(false);

        jLabel4.setText(" 生成只有对应的用户才可以读取的数据文件");
        jLabel4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("设定用户名");

        userAlise.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        userAlise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userAlise.setText("aabbc");

        loadKeyButton.setText("读取key");

        jMenu1.setText("File");

        optionButton.setText("设置");
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });
        jMenu1.add(optionButton);

        quitButton.setText("退出");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        jMenu1.add(quitButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(registButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(loadKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userAlise, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addComponent(key)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userAlise, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(loadKeyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
}// </editor-fold>//GEN-END:initComponents

private void registButtonActionPerformed(ActionEvent evt) {
	String user = readUtils.read("user");
	if(user !=null && !user.isEmpty()) {
		TransferToSqlite transfer = new TransferToSqlite("abc", key.getText(), readUtils.read("sourceTable"), readUtils.read("targetTable"));
		try {
			transfer.open(readUtils.read("file"));
			int page = transfer.getTotalPage();
			JProgressBar progressBar = new JProgressBar(0, page);
			JDialog dialog = new JDialog(this);
			dialog.add(progressBar);
			dialog.setAlwaysOnTop(true);
			progressBar.setValue(0);
			progressBar.setVisible(true);
			progressBar.setString("正在生成用户数据");
			dialog.setLocationRelativeTo(null);
			dialog.setVisible(true);
			dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
			for (int i = 1; i <= page; i++) {
				if (transfer.transfer(i)) {
					progressBar.setValue(i);
				}
			}
			dialog.dispose();
			Toolkit.getDefaultToolkit().beep();
			JOptionPane.showMessageDialog(this,"请将生成的数据文件发给用户：\n" + transfer.getPath(), "注册完成", JOptionPane.INFORMATION_MESSAGE);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (NoSuchPaddingException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (InvalidKeyException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (IllegalBlockSizeException e) {
			e.printStackTrace();
		} catch (BadPaddingException e) {
			e.printStackTrace();
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}else{
		Toolkit.getDefaultToolkit().beep();
		JOptionPane.showMessageDialog(this, "请先配置好数据库连接！", "提示", JOptionPane.WARNING_MESSAGE);
	}
}

private void optionButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
	JDialog dialog = new JDialog(this);
	dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	dialog.add(new OptionView(readUtils));
	dialog.setTitle("设置");
	dialog.setVisible(true);
	dialog.setSize(400, 250);
	dialog.setResizable(false);
	dialog.setLocationRelativeTo(null);
}//GEN-LAST:event_optionButtonActionPerformed

private void quitButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
	System.exit(0);
}//GEN-LAST:event_quitButtonActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
		/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
	try {
		for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	} catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

        /* Create and display the form */
	EventQueue.invokeLater(new Runnable() {
		public void run() {
			new Register().setVisible(true);
		}
	});
}

// Variables declaration - do not modify//GEN-BEGIN:variables
private JLabel jLabel1;
private JLabel jLabel2;
private JLabel jLabel3;
private JLabel jLabel4;
private JLabel jLabel5;
private JMenu jMenu1;
private JMenuBar jMenuBar1;
private JTextField key;
private JMenuItem optionButton;
private JMenuItem quitButton;
private JButton registButton;
private JTextField userAlise;    
private javax.swing.JButton loadKeyButton;
private ReadUtils readUtils = new ReadUtils();
// End of variables declaration//GEN-END:variables
}
